// Code generated by gop (Go+); DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goplus/cobra"
)

const _ = true

type App struct {
	cobra.App
}
type version struct {
	cobra.Command
	*App
}

func (this *App) MainEntry() {
}
func (this *App) Classprojname() string {
	return "godemo"
}
func (this *App) Main() {
	cobra.Gopt_App_Main(this, new(version))
}
//line demo/godemo/version_cmd.gox:1
func (this *version) Main(_gop_arg0 string) {
	this.Command.Main(_gop_arg0)
//line demo/godemo/version_cmd.gox:1:1
	this.Short("print Go version")
//line demo/godemo/version_cmd.gox:3:1
	this.Long(`Version prints the build information for Go binary files.

Go version reports the Go version used to build each of the named files.

If no files are named on the command line, go version prints its own
version information.

If a directory is named, go version walks that directory, recursively,
looking for recognized Go binaries and reporting their versions.
By default, go version does not report unrecognized files found
during a directory scan. The -v flag causes it to report unrecognized files.

The -m flag causes go version to print each file's embedded
module version information, when available. In the output, the module
information consists of multiple lines following the version line, each
indented by a leading tab character.

See also: go doc runtime/debug.BuildInfo.
`)
//line demo/godemo/version_cmd.gox:23:1
	this.Run(func() {
//line demo/godemo/version_cmd.gox:24:1
		fmt.Println("go1.0")
	})
}
func (this *version) Classfname() string {
	return "version"
}
func main() {
//line demo/godemo/version_cmd.gox:23:1
	new(App).Main()
}
